In [3]:
import numpy as np
import pandas as pd
import sys
sys.path.append('/Users/arthurzhou/github/aps360_project')
sys.path.append(r'C:\Users\Arthur Zhou\GitHub\aps360_project')
from src.data.data_utils import load_data, compare_single_fitness
%load_ext autoreload
%autoreload 2

### Comparing differences in experimental measures
Both single and continuous sets have fitness scores for single mutants. In some cases, the difference may be too large. We want to quantify these cases to check the quality of our data

### Load both processed datasets

In [64]:
root_ = '/Users/arthurzhou/github/aps360_project/src/data/raw/dms'
single_df = load_data(root_ +'/dms_single.xlsx', 'single')
double_df = load_data(root_ +'/dms_pair.xlsx','pair')

/Users/arthurzhou/miniconda3/envs/aps360/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

Data loaded. Prior size: 5741, After dropna: 5740
Data loaded. Prior size: 12374, After dropna: 12374

In [67]:
single_double, stats, error_inter_indx_s, error_inter_indx_d = compare_single_fitness(single_df, double_df, 1)
stats

{'single_in_double': np.int64(9181),
 'single_in_double_ratio': np.float64(0.6908721498984122),
 'double_in_single': np.int64(10055),
 'double_in_single_ratio': np.float64(0.7566408307622846),
 'error_intersection': np.int64(10230),
 'error_intersection_ratio': np.float64(0.7698096169764467)}

In [ ]:
from rdflib import Graph
g = Graph()

g.parse('/Users/arthurzhou/github/aps360_project/src/data/raw/aa_index/CHAM810101.ttl', format='turtle')
for s, p, o in g:
    print(s, p, o)
pd.read_csv('/Users/arthurzhou/github/aps360_project/src/data/raw/aa_index/CHAM810101.ttl')

  <https://www.genome.jp/dbget-bin/www_bget?aaindex:CHAM810101>\t<https://www.genome.jp/linkdb/original>\t<https://www.genome.jp/dbget-bin/www_bget?aaindex:FAUJ880102>\t.
0  <https://www.genome.jp/dbget-bin/www_bget?aain...
1  <https://www.genome.jp/dbget-bin/www_bget?aain...
2  <https://www.genome.jp/dbget-bin/www_bget?aain...
3  <https://www.genome.jp/dbget-bin/www_bget?aain...
4  <https://www.genome.jp/dbget-bin/www_bget?aain...
5  <https://www.genome.jp/dbget-bin/www_bget?aain...

In [68]:
double_df

,Position of First Mut,Ambler Position,WT AA 1,WT AA 2,Mut AA 1,Mut AA 2,Mut 1 Fitness,Mut 1 Fitness Error,Mut 2 Fitness,Mut 2 Fitness Error,Double Mutant Fitness,Double Mutant Fitness Error,Epistasis,Upper Level Fractional Error,Lower Level Fractional Error,Positive Sign Epistasis,Negative Sign Epistasis,Unnamed: 17,Unnamed: 18
0,1,3,M,S,R,C,0.002063,0.000269,0.570203,0.084343,0.003714,0.000487,NaN,NaN,NaN,NaN,NaN,,NaN
1,1,3,M,S,I,R,0.416689,0.045892,0.689897,0.066357,0.007162,0.001334,-1.603535,-1.551035,-1.663265,NaN,NaN,NaN,NaN
2,1,3,M,S,T,G,0.063085,0.008628,0.417242,0.037710,0.010936,0.000721,-0.381459,-0.337224,-0.430717,NaN,NaN,NaN,NaN
3,1,3,M,S,I,G,0.416689,0.045892,0.417242,0.037710,0.011411,0.000447,-1.182876,-1.135091,-1.236577,NaN,NaN,NaN,NaN
4,1,3,M,S,I,T,0.416689,0.045892,1.139504,0.178914,0.059792,0.009567,-0.899889,-0.817011,-1.002403,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12369,285,289,H,W,W,G,NaN,NaN,0.006298,0.000497,0.003603,0.000191,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12370,285,289,H,W,E,A,0.839944,0.166490,NaN,NaN,0.001252,0.000204,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12371,285,289,H,W,R,A,0.931093,0.083061,NaN,NaN,0.001235,0.000096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12372,285,289,H,W,A,A,0.649188,0.067464,NaN,NaN,0.000956,0.000086,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12373,285,289,H,W,L,A,0.660828,0.055656,NaN,NaN,0.000811,0.000137,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
double_df[~double_df.index.isin(error_inter_indx_d)]

,Position of First Mut,Ambler Position,WT AA 1,WT AA 2,Mut AA 1,Mut AA 2,Mut 1 Fitness,Mut 1 Fitness Error,Mut 2 Fitness,Mut 2 Fitness Error,Double Mutant Fitness,Double Mutant Fitness Error,Epistasis,Upper Level Fractional Error,Lower Level Fractional Error,Positive Sign Epistasis,Negative Sign Epistasis,Unnamed: 17,Unnamed: 18
0,1,3,M,S,R,C,0.002063,0.000269,0.570203,0.084343,0.003714,0.000487,NaN,NaN,NaN,NaN,NaN,,NaN
1,1,3,M,S,I,R,0.416689,0.045892,0.689897,0.066357,0.007162,0.001334,-1.603535,-1.551035,-1.663265,NaN,NaN,NaN,NaN
3,1,3,M,S,I,G,0.416689,0.045892,0.417242,0.037710,0.011411,0.000447,-1.182876,-1.135091,-1.236577,NaN,NaN,NaN,NaN
4,1,3,M,S,I,T,0.416689,0.045892,1.139504,0.178914,0.059792,0.009567,-0.899889,-0.817011,-1.002403,NaN,NaN,NaN,NaN
7,1,3,M,S,R,G,0.002063,0.000269,0.417242,0.037710,0.001839,0.000266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12368,285,289,H,W,L,C,0.660828,0.055656,0.002603,0.000311,0.000837,0.000172,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12370,285,289,H,W,E,A,0.839944,0.166490,NaN,NaN,0.001252,0.000204,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12371,285,289,H,W,R,A,0.931093,0.083061,NaN,NaN,0.001235,0.000096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12372,285,289,H,W,A,A,0.649188,0.067464,NaN,NaN,0.000956,0.000086,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12373,285,289,H,W,L,A,0.660828,0.055656,NaN,NaN,0.000811,0.000137,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
single_df[~single_df.index.isin(error_inter_indx_s)]

,Ambler Position,WT AA,Mutant AA,Sequencing Counts for each sub-library,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Total Counts,Fitness,Estimated error in fitness
1,3.0,M,A,6.0,22.0,12,3,4,4,0,0,0,0,0,0,0,51.0,0.002018,0.000294
2,3.0,M,C,0.0,8.0,17,4,0,0,0,0,1,1,0,2,0,33.0,0.003023,0.000522
3,3.0,M,D,0.0,7.0,5,0,0,0,0,0,0,0,0,0,0,12.0,0.002220,0.000567
4,3.0,M,E,0.0,15.0,16,0,0,0,0,0,0,0,0,0,0,31.0,0.002378,0.000421
5,3.0,M,F,0.0,0.0,2,7,0,0,0,0,0,0,0,1,0,10.0,0.005702,0.001562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5736,291.0,*,S,0.0,0.0,0,0,0,0,0,0,0,0,2,0,0,2.0,NaN,NaN
5737,291.0,*,T,0.0,0.0,0,1,0,0,0,0,0,2,17,0,0,20.0,0.791548,0.165813
5738,291.0,*,V,1.0,6.0,0,1,0,0,0,0,0,0,17,0,0,25.0,0.851460,0.163613
5739,291.0,*,W,0.0,0.0,0,0,0,0,0,0,0,0,0,1,0,1.0,NaN,NaN
5740,291.0,*,Y,0.0,0.0,1,2,0,0,0,0,0,0,5,0,0,8.0,0.851460,0.254240

### PDB loading

In [125]:
from src.data.data_utils import load_cif_structure, parse_structure

structure = load_cif_structure(r'C:\Users\Arthur Zhou\GitHub\aps360_project\src\data\raw\1BTL.cif', '1ZG4')
sequence, atomic_coords, distance_matrices, nearest_neighbors = parse_structure(structure)

In [126]:
len(sequence), atomic_coords['CA'].shape, distance_matrices['CA'].shape, nearest_neighbors['CA'].shape

(263, (263, 3), (263, 263), (263, 20))

In [145]:
a[:,0][[0,1],:] - b[:,0][[2,3],:]

array([[-1., -1., -1.],
       [-1., -1., -1.]])

In [ ]:
np.concatenate([np.zeros((6,1,3)), np.ones((6,1,3))], axis=1).shape

(6, 4, 3)

In [153]:
a = np.ones((6,4, 3))
b = np.full((6,4, 3), 2.0)

np.linalg.norm(a, axis=-1).shape

(6, 4)

In [ ]:
distance_matrices['CA']

(263, 3)